improved debugging output and logging

diff --git a/build_features b/build_features
--- a/build_features
+++ b/build_features
@@ -3,12 +3,13 @@
 # error out if we try to use an unset variable
 set -u
 
+debug=${debug:-1}
 featureset="${1:-}"
 
 if [ ! "$featureset" ]; then
-  echo "Usage: $0 {featureset}"
-  echo " from the folder containing a features and feature_sets folders"
-  echo "current featuresets: $(find feature_sets -mindepth 1 -maxdepth 1 -not -name '.*' -type f -printf "%f ")"
+  err "Usage: $0 {featureset}"
+  err " from the folder containing a features and feature_sets folders"
+  err "current featuresets: $(find feature_sets -mindepth 1 -maxdepth 1 -not -name '.*' -type f -printf "%f ")"
   exit 1
 fi
 
@@ -31,14 +32,15 @@ verify_dependencies() {
         fi
       done
       if [ ! "$found" ]; then 
-        echo "error: feature [$feature] requires [$dependency] to be present earlier in the featureset"
+        err "error: feature [$feature] requires [$dependency] to be present earlier in the featureset"
         return 1
       fi
     done
   fi
 }
 
-for file in $(find lib -mindepth 1 -maxdepth 1 -not -name ".*" -type f); do
+source lib/common || exit 1
+for file in $(find lib -mindepth 1 -maxdepth 1 -not -name common -not -name ".*" -type f); do
   source $file || exit 1
 done
 
@@ -66,10 +68,10 @@ process_features() {
   local feature features="" fp 
   for feature in $(cat_no_comments feature_sets/$featureset); do
     if [ ! -d features/$feature ]; then
-      echo "error: missing feature: $feature"
+      err "error: missing feature: $feature"
       exit 1
     fi
-    echo "Before feature: $feature"
+    out "Before feature: $feature"
 
     verify_dependencies || exit 1
     fp=features/$feature
@@ -89,7 +91,7 @@ process_features() {
   for feature in "${features[@]}"; do
     fp=features/$feature
     if [ -f "$fp/after" ]; then
-      echo "After feature: $feature"
+      out "After feature: $feature"
       cd $fp || exit 1
       source ./after || exit 1
       cd ../.. || exit 1
diff --git a/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent b/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
--- a/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
+++ b/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
@@ -1,15 +1,16 @@
 #!/bin/bash
 
 if [ ! -d lib ]; then
-  echo "Missing lib folder. Make sure you run this script a place with the lib folder and arms_agent.config"
+  err "Missing lib folder. Make sure you run this script a place with the lib folder and arms_agent.config"
   exit 1
 fi
 
-for file in $(find lib -mindepth 1 -maxdepth 1 -not -name ".*" -type f); do
+source lib/common || exit 1
+for file in $(find lib -mindepth 1 -maxdepth 1 -not -name common -not -name ".*" -type f); do
   source $file || exit 1
 done
 
-lock arms || { echo "arms agent is already running"; exit 1; }
+lock arms || { err "arms agent is already running"; exit 1; }
 
 dbexecute() {
 out "dbexecute $1"
@@ -17,13 +18,13 @@ mysql_query "$1" || return 1
 }
 
 if [ ! -f arms_agent.config ]; then
-  echo "Missing arms_agent.config. It must exist in the current directory."
+  err "Missing arms_agent.config. It must exist in the current directory."
   exit 1
 fi
 
 source arms_agent.config
 requireVar host_id db_host db_name db_user db_pass || {
-  echo "Make sure that you have defined this variable in your arms_agent.config file"
+  err "Make sure that you have defined this variable in your arms_agent.config file"
   exit 1
 }
 
@@ -66,7 +67,7 @@ try
       insert into output set
         creation_time=now()
         , content='$content'
-      " || { echo "couldn't insert record into output table."; fail }
+      " || { err "couldn't insert record into output table."; fail }
 
     dbfetch_single_value "select last_insert_id()" || fail
     output_id=$r
@@ -97,7 +98,7 @@ try
       , event_time=now()
       , new_status='done'
       , result='$job_status'
-    " || { echo "failed to insert task change record."; fail }
+    " || { err "failed to insert task change record."; fail }
 
   cd .. || fail
   rm -rf job_${job_id} 
@@ -117,7 +118,7 @@ try
     where host_id = $host_id
     and tsc.task_request_id is null
     limit 1
-    " || { echo "failed to fetch new tasks."; fail }
+    " || { err "failed to fetch new tasks."; fail }
 end_try
 handle_return
 }
@@ -125,13 +126,13 @@ handle_return
 launch_task() {
 out "launch_task job_id=$job_id task_request_id=$task_request_id"
 try
-  grab_row task_request_id script_content script_parameters || { echo "failed to get row from array."; fail }
+  grab_row task_request_id script_content script_parameters || { err "failed to get row from array."; fail }
   dbexecute "
   insert into task_status_change set
     task_request_id = $task_request_id
     , event_time = now()
     , new_status = 'started'
-  " || { echo "failed to update task status."; fail }
+  " || { err "failed to update task status."; fail }
 
   mkdir job_${job_id} || fail
   cd job_${job_id} || fail
@@ -153,7 +154,7 @@ main_loop() {
 local iteration=1 short_sleep
 min_wait=${min_wait:-50}
 max_wait=${max_wait:-70}
-out "main_loop()"
+out "main_loop"
 try
   while true; do 
     if grab_completed_process; then
@@ -165,16 +166,25 @@ try
   done
 
   if can_launch_more_processes; then
+    out "We have more room for processes"
     fetch_a_task || fail
 
     if more_rows_to_read; then
+      out "Found a task"
       launch_task || fail
       short_sleep=1
+    else
+      out "No tasks to do"
     fi
+  else
+    out "No room for more processes"
   fi
 
   iteration=$((iteration+1))
-  [ "$max_iterations" ] && [[ $iteration > $max_iterations ]] && break
+  [ "$max_iterations" ] && [[ $iteration > $max_iterations ]] && {
+    out "Max iterations reached ($iteration > $max_iterations)"
+    break
+  }
 
   # there's nothing to do right now, let's rest a bit before trying again
   if [[ $max_wait > 0 ]]; then
diff --git a/features/hosted_agents_connect_to_db_and_execute_tasks/tests/agent_execution/simple_task_execution b/features/hosted_agents_connect_to_db_and_execute_tasks/tests/agent_execution/simple_task_execution
--- a/features/hosted_agents_connect_to_db_and_execute_tasks/tests/agent_execution/simple_task_execution
+++ b/features/hosted_agents_connect_to_db_and_execute_tasks/tests/agent_execution/simple_task_execution
@@ -47,21 +47,20 @@ EOF
   out "Checking results in db..."
   [[ $(echo "select count(*) from task_status_change 
             where new_status='started' and task_request_id=1" | dbexecute $central_db_name) == 1 ]] || {
-      echo "Missing proper 'started' task_status_change record"
+      err "Missing proper 'started' task_status_change record"
       fail
      }
   [[ $(echo "select count(*) from task_status_change 
             where new_status='done' and task_request_id=1 and result='succeeded'" | dbexecute $central_db_name) == 1 ]] || {
-      echo "Missing proper 'done' task_status_change record"
+      err "Missing proper 'done' task_status_change record"
       fail
      }
 
   cd $OLDPWD || fail
 
 end_try
-
 handle_return
 }
 
-debug=1 run_test
+debug=2 run_test || return 1
 
diff --git a/lib/bash_templates b/lib/bash_templates
--- a/lib/bash_templates
+++ b/lib/bash_templates
@@ -3,17 +3,15 @@
 # usage: cat file | hydrate_template >output
 #   will replace bash variables and expressions
 hydrate_template() {
-local returnValue=0
 local OIFS="$IFS"
-while true; do
-    IFS=$'\n'
+try
+  IFS=$'\n'
     while read -r line; do
-        line="${line//\"/\\\"}"
-        eval "echo \"$line\"" || fail
+      line="${line//\"/\\\"}"
+      eval "echo \"$line\"" || fail
     done
-    break
-done
+end_try
 IFS="$OIFS"
-return $returnValue
+handle_return
 }
 
diff --git a/lib/mysql_connection_pooling b/lib/mysql_connection_pooling
--- a/lib/mysql_connection_pooling
+++ b/lib/mysql_connection_pooling
@@ -80,7 +80,7 @@ function mysql_connect {
     fi
 
     if [[ ${#user} < 1 || ${#db} < 1 ]]; then
-      echo "ERROR: Options user and db are required!"
+      err "ERROR: Options user and db are required!"
       fail
     fi
 
@@ -91,9 +91,9 @@ function mysql_connect {
     HANDLE=$(eval 'echo ${'${HANDLEID}'[0]}_${'${HANDLEID}'[1]}_${'${HANDLEID}'_PID}')
     if mysql_check $HANDLE; then
       export HANDLE
-      return 0
+      break
     else
-      echo "ERROR: Connection failed to $user@$host->DB:$db!"
+      err "ERROR: Connection failed to $user@$host->DB:$db!"
       fail
     fi
   end_try
@@ -106,10 +106,12 @@ function mysql_connect {
 #         $DATA[2] = key1; DATA[3] = val1
 #         $DATA[4] = key2; DATA[5] = val2 (depending on number of columns, rows)
 function mysql_query {
-  local handle query affected line results_open row_open cols key val
+  local handle query affected line results_open row_open cols key val timed_out
+  query=$1
+  out "mysql_query ${query:0:40}"
   try
     if ! mysql_check $HANDLE; then
-      echo "ERROR: Connection not open!"
+      err "ERROR: Connection not open!"
       return 1
     fi
     handle=(${HANDLE//_/ })
@@ -118,7 +120,6 @@ function mysql_query {
     export current_row=0
 
     # delimit query; otherwise we block forever/timeout
-    query=$2
     if [[ ! "$query" =~ \;\$ ]]; then
       query="$query;"
     fi
@@ -136,14 +137,14 @@ function mysql_query {
     do
       # WAS ERROR?
       if [[ "$line" == *"ERROR"* ]]; then
-        echo "$line"
-        return 1
+        err "$line"
+        fail
       # WAS INSERT/UPDATE?
       elif [[ "$line" == *"Query OK"* ]]; then
         affected=$([[ "$line" =~ Query\ OK\,\ ([0-9]+)\ rows?\ affected ]] && echo ${BASH_REMATCH[1]})
         DATA[0]=$affected
         export DATA
-        return 0
+        break
       fi
 
       # BEGIN FETCHING RESULTS
@@ -173,21 +174,20 @@ function mysql_query {
       #END OF RESULTS
       if [[ $line =~ \<\/resultset ]]; then
         export DATA
-        return 0
+        break
       fi
     done
-    #we can only get here
-    #if read times out O_o
-    echo "$FUNCNAME: Read timed out!"
+    [[ $? > 0 ]] && [[ return_value == 0 ]] && {
+      err "$FUNCNAME: Read timed out!"
+      fail
+    }
+    maybe_break
   end_try
-  handle_return # was return 1
+  handle_return
 }
 
 # returns true if the previous mysql_query command returned 1 or more rows
 function more_rows_to_read {
-  if [ ! "${DATA:-}" ]; then
-    return 1
-  fi
   if [[ ${DATA[0]} > $current_row ]]; then
     return 0
   fi
@@ -223,7 +223,7 @@ fi
 function mysql_close {
   local handle
   if ! mysql_check $1; then
-    echo "ERROR: Connection not open!"
+    err "ERROR: Connection not open!"
     return 1
   fi
   handle=(${1//_/ })
@@ -232,7 +232,7 @@ function mysql_close {
   if ! mysql_check $1; then
     return 0
   else
-    echo "ERROR: Couldn't close connection!"
+    err "ERROR: Couldn't close connection!"
     return 1
   fi
 }
