got simple_test_execution test working

diff --git a/features/hosted_agents_connect_to_db_and_execute_tasks/tests/agent_execution/simple_task_execution b/features/hosted_agents_connect_to_db_and_execute_tasks/tests/agent_execution/simple_task_execution
--- a/features/hosted_agents_connect_to_db_and_execute_tasks/tests/agent_execution/simple_task_execution
+++ b/features/hosted_agents_connect_to_db_and_execute_tasks/tests/agent_execution/simple_task_execution
@@ -3,9 +3,7 @@
 while true; do
   returnValue=0
 
-  cat <<EOF | dbexecute || fail
-use $central_db_name;
-
+  cat <<EOF | dbexecute $central_db_name || fail
 insert into host set
   host_id = 1
   , name = 'test_host'
@@ -38,6 +36,15 @@ host_id=1
 EOF
 
   bin/arms_agent || fail
+
+  [ $(echo "select count(*) from task_status_change where host_id=1 and new_status='started' and task_request_id=1" | dbexecute $central_db_name) == 1 ] || {
+      echo "Missing proper 'started' task_status_change record"
+      fail
+     }
+  [ $(echo "select count(*) from task_status_change where host_id=1 and new_status='succeeded' and task_request_id=1" | dbexecute $central_db_name) == 1 ] || {
+      echo "Missing proper 'succeeded' task_status_change record"
+      fail
+     }
 
   cd $OLDPWD || fail
 
