minor

diff --git a/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent b/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
--- a/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
+++ b/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
@@ -41,8 +41,68 @@ establish_connection() {
 
 establish_connection
 
+# usage: insert_into_output_table {file_name containing content}
+# if file doesn't exist, returns true but no output_id
+# returns 1 if anything fails
+# sets output_id to inserted id if record was successfully inserted
+insert_into_output_table() {
+local file_name=$1
+local content id
+local returnValue=0
+unset output_id
 while true; do
-  ... check for completed processes
+  if [ -f $file_name ]; then
+    eval "content=\$(<$file_name)"
+    content=${content//'/\\'}
+
+    dbexecute "
+      insert into output set
+        creation_time=now()
+        , content='$content'
+      " || (echo "couldn't insert record into output table."; fail)
+
+    dbfetch_single_value "select last_insert_id()" || fail
+    output_id=$r
+
+  fi
+  break
+done
+
+handleReturn
+}
+
+main_loop() {
+local returnValue=0
+while true; do
+  while true; do 
+    if grab_completed_process; then
+      cd job_${job_id} || fail
+
+      local job_status=failed
+      [ -f succeeded ] && job_status=succeeded
+
+      insert_into_output_table output || fail
+      local oid=output_id
+      insert_into_output_table error || fail
+      local eid=output_id
+
+      dbexecute "
+        insert into task_status_change set 
+          task_request_id=$(<task_request_id)
+          , output_id=$oid
+          , error_id=$eid
+          , event_time=now()
+          , new_status='done'
+          , result='$job_status'
+        " || (echo "failed to insert task change record."; fail)
+
+      cd .. || fail
+      rm -rf job_${job_id} 
+      
+      continue # we need to keep pulling completed processes out until they are gone
+    fi
+    break
+  done
 
   if can_launch_more_processes; then
     # grab a task to do
@@ -68,8 +128,9 @@ while true; do
 
       mkdir job_${job_id} || fail
       cd job_${job_id} || fail
-      echo "$script_content" >request_$task_request_id || fail
-      sh request_$task_request_id $script_parameters >output 2>error </dev/null &
+      echo "$task_request_id" >task_request_id || fail
+      echo "$script_content" >request || fail
+      sh request $script_parameters >output 2>error </dev/null &
       track_process || fail
       cd .. || fail
     fi
@@ -77,7 +138,16 @@ while true; do
 
   # there's nothing to do right now, let's rest a bit before trying again
   random_sleep 50 70
+
+  # loop forever, unless we hit a critical failure
 done
 
+handleReturn
+}
+
+main_loop || exit 1
+
+# It's okay if exit happens before the lock is released. 
+# Stale locks are automatically cleaned up when this script starts.
 unlock arms &>/dev/null
 
