added process_tracking

diff --git a/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent b/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
--- a/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
+++ b/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
@@ -5,11 +5,15 @@ if [ ! -d lib ]; then
   exit 1
 fi
 
+agent_tmp=/tmp/arms_agent
+rm -rf $agent_tmp &>/dev/null
+mkdir $agent_tmp || exit 1
+cd $agent_tmp || exit 1
+
 source lib/* || exit 1
 
 lock arms &>/dev/null || (echo "arms agent is already running"; exit 1)
 
-unset dbexecute
 dbexecute() {
 mysql_query "$1" || return 1
 }
@@ -25,7 +29,12 @@ requireVar host_id db_host db_user db_pass || {
   exit 1
 }
 
-unset establish_connection
+# optional variables which may be set in arms_agent.config
+
+# max_processes : maximum number of processes to run at once
+
+initialize_process_tracking ${max_processes:-4}
+
 establish_connection() {
   host=$db_host user=$db_user pass=$db_pass mysql_connect || return 1
 }
@@ -33,27 +42,41 @@ establish_connection() {
 establish_connection
 
 while true; do
-  # grab a task to do
-  dbexecute "
-    select tr.task_request_id, s.content, tr.parameters 
-    from task_request_not_done trnd 
-    inner join task_request tr using (task_request_id)
-    inner join script s using (script_id)
-    left join task_status_change tsc on trnd.task_request_id = tsc.task_request_id
-    where host_id = $host_id
-    and tsc.task_request_id is null
-    limit 1
-    " || (echo "failed to fetch new tasks."; fail)
+  ... check for completed processes
 
-  if more_rows_to_read; then
-    grab_row task_request_id script_content script_parameters || (echo "failed to get row from array."; fail)
+  if can_launch_more_processes; then
+    # grab a task to do
     dbexecute "
-    " | (echo "failed to update task status."; fail)
-  else 
-    # there's nothing to do right now, let's rest a bit before trying again
-    random 10
-    sleep $((60+result))
+      select tr.task_request_id, s.content, tr.parameters 
+      from task_request_not_done trnd 
+      inner join task_request tr using (task_request_id)
+      inner join script s using (script_id)
+      left join task_status_change tsc on trnd.task_request_id = tsc.task_request_id
+      where host_id = $host_id
+      and tsc.task_request_id is null
+      limit 1
+      " || (echo "failed to fetch new tasks."; fail)
+
+    if more_rows_to_read; then
+      grab_row task_request_id script_content script_parameters || (echo "failed to get row from array."; fail)
+      dbexecute "
+      insert into task_status_change set
+        task_request_id = $task_request_id
+        , event_time = now()
+        , new_status = 'started'
+      " || (echo "failed to update task status."; fail)
+
+      mkdir job_${job_id} || fail
+      cd job_${job_id} || fail
+      echo "$script_content" >request_$task_request_id || fail
+      sh request_$task_request_id $script_parameters >output 2>error </dev/null &
+      track_process || fail
+      cd .. || fail
+    fi
   fi
+
+  # there's nothing to do right now, let's rest a bit before trying again
+  random_sleep 50 70
 done
 
 unlock arms &>/dev/null
