tests passing

diff --git a/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent b/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
--- a/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
+++ b/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
@@ -57,21 +57,26 @@ establish_connection || exit 1
 insert_into_output_table() {
 local file_name=$1
 local content id
-unset output_id
+output_id=null
 out "insert_into_output_table $file_name"
 try
   if [ -f $file_name ]; then
     eval "content=\$(<$file_name)"
     content=${content//'/\\'}
+    if [ "$content" ]; then
+      dbexecute "
+        insert into output set
+          creation_time=now()
+          , content='$content'
+        " || { err "couldn't insert record into output table."; fail }
 
-    dbexecute "
-      insert into output set
-        creation_time=now()
-        , content='$content'
-      " || { err "couldn't insert record into output table."; fail }
-
-    dbfetch_single_value "select last_insert_id()" || fail
-    output_id=$r
+      dbfetch_single_value "select last_insert_id()" || fail
+      output_id=$r
+    else
+      out "file exists, but has no content, so no output will be recorded."
+    fi
+  else
+    out "file $file_name doesn't exist, so no output will be recorded."
   fi
 end_try
 
@@ -87,9 +92,9 @@ try
   [ -f succeeded ] && job_status=succeeded
 
   insert_into_output_table output || fail
-  local oid=output_id
+  local oid=$output_id
   insert_into_output_table error || fail
-  local eid=output_id
+  local eid=$output_id
 
   dbexecute "
     insert into task_status_change set 
@@ -125,7 +130,7 @@ handle_return
 }
 
 launch_task() {
-out "launch_task job_id=$job_id task_request_id=$task_request_id"
+out "launch_task job_id=$job_id"
 try
   grab_row task_request_id script_content script_parameters || { err "failed to get row from array."; fail }
   dbexecute "
@@ -141,12 +146,13 @@ try
   echo "$script_content" >request || fail
   if [ "$synchronous" ]; then
     sh request $script_parameters >output 2>error </dev/null
+    cd .. || fail
     record_results_of_completed_process || fail
   else
     sh request $script_parameters >output 2>error </dev/null &
     track_process || fail
+    cd .. || fail
   fi
-  cd .. || fail
 end_try
 handle_return
 }
@@ -155,7 +161,7 @@ main_loop() {
 local iteration=1 short_sleep
 min_wait=${min_wait:-50}
 max_wait=${max_wait:-70}
-out "main_loop"
+out "arms_agent main_loop"
 try
   while true; do 
     if grab_completed_process; then
