lots of changes

diff --git a/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent b/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
--- a/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
+++ b/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
@@ -12,10 +12,6 @@ done
 
 lock arms || { err "arms agent is already running"; exit 1; }
 
-dbexecute() {
-mysql_query "$1" || return 1
-}
-
 if [ ! -f arms_agent.config ]; then
   err "Missing arms_agent.config. It must exist in the current directory."
   exit 1
@@ -64,11 +60,11 @@ try
     eval "content=\$(<$file_name)"
     content=${content//'/\\'}
     if [ "$content" ]; then
-      dbexecute "
+      echo "
         insert into output set
           creation_time=now()
           , content='$content'
-        " || { err "couldn't insert record into output table."; fail }
+        " | mysql_query || { err "couldn't insert record into output table."; fail }
 
       dbfetch_single_value "select last_insert_id()" || fail
       output_id=$r
@@ -96,7 +92,7 @@ try
   insert_into_output_table error || fail
   local eid=$output_id
 
-  dbexecute "
+  echo "
     insert into task_status_change set 
       task_request_id=$(<task_request_id)
       , output_id=$oid
@@ -104,7 +100,7 @@ try
       , event_time=now()
       , new_status='done'
       , result='$job_status'
-    " || { err "failed to insert task change record."; fail }
+    " | mysql_query || { err "failed to insert task change record."; fail }
 
   cd .. || fail
   rm -rf job_${job_id} 
@@ -115,7 +111,7 @@ handle_return
 fetch_a_task() {
 out "fetch_a_task"
 try
-  dbexecute "
+  echo "
     select tr.task_request_id, s.content, tr.parameters 
     from task_request_not_done trnd 
     inner join task_request tr using (task_request_id)
@@ -124,7 +120,7 @@ try
     where host_id = $host_id
     and tsc.task_request_id is null
     limit 1
-    " || { err "failed to fetch new tasks."; fail }
+    " | mysql_query || { err "failed to fetch new tasks."; fail }
 end_try
 handle_return
 }
@@ -133,12 +129,12 @@ launch_task() {
 out "launch_task job_id=$job_id"
 try
   grab_row task_request_id script_content script_parameters || { err "failed to get row from array."; fail }
-  dbexecute "
+  echo "
   insert into task_status_change set
     task_request_id = $task_request_id
     , event_time = now()
     , new_status = 'started'
-  " || { err "failed to update task status."; fail }
+  " | mysql_query || { err "failed to update task status."; fail }
 
   mkdir job_${job_id} || fail
   cd job_${job_id} || fail
diff --git a/lib/mysql_connection_pooling b/lib/mysql_connection_pooling
--- a/lib/mysql_connection_pooling
+++ b/lib/mysql_connection_pooling
@@ -13,7 +13,7 @@
 #  user=mydbuser db=mydb host=myhost mysql_connect 
 #  
 #  #query db and get $DATA
-#  mysql_query "SELECT dt_whatever from tbl_lol WHERE dt_rofl=10"
+#  echo "SELECT dt_whatever from tbl_lol WHERE dt_rofl=10" | mysql_query 
 #  
 #  #close connection
 #  mysql_close
@@ -51,51 +51,68 @@
 # set a default here
 export MYSQL_READ_TIMEOUT=10
 
-#args handle query
+# usage: HANDLE={connection handle} mysql_check 
 function mysql_check {
-  local handle
-  handle=(${1//_/ })
-  #has right structure && is still running && we opened it?
-  if [[ ${#handle[*]} == 3 ]] && ps -p ${handle[2]} 2>> /dev/null >> /dev/null && { echo "" >&${handle[1]}; } 2> /dev/null; then
-    return 0
-  fi
-  return 1
+  out "mysql_check"
+  try
+    local handle
+    handle=(${HANDLE//_/ })
+    if [[ ${#handle[*]} != 3 ]]; then
+      err "HANDLE structure is wrong: HANDLE=$HANDLE"
+      fail
+    fi
+    if ! ps ${handle[2]} &>/dev/null; then
+      err "Process ${handle[2]} is not running."
+      err "ps ${handle[2]}: $(ps ${handle[2]})"
+      fail
+    fi
+    if ! echo "" >&${handle[1]}; then
+      err "Can't write to file descriptor ${handle[1]}"
+      fail
+    fi
+    out "successful connection check"
+  end_try
+  handle_return
 }
 
 # open mysql connection
 # usage: user="myuser" pass="mypass" host="myhost" db="mydb" mysql_connection
-#   host and pass are optional
+#   host, db, user, and pass are optional
 # returns $HANDLE
 function mysql_connect {
   local argv argc HANDLEID i
-  out "mysql_connect host=$host db=$db user=$user pass=$pass"
+  out "mysql_connect host=${host:-} db=${db:-} user=${user:-} pass=${pass:-}"
   try
     #prepare args
     argv=($*)
     argc=${#argv[*]}
 
-    host="${host:-localhost}"
-    if [ "$pass" ]; then
-      pass="-p$pass"
+    if [ "${host:-}" ]; then
+      host="-h $host "
     fi
-
-    if [[ ${#user} < 1 || ${#db} < 1 ]]; then
-      err "ERROR: Options user and db are required!"
-      fail
+    if [ "${db:-}" ]; then
+      db="-D $db "
+    fi
+    if [ "${user:-}" ]; then
+      user="-u $user "
+    fi
+    if [ "${pass:-}" ]; then
+      pass="-p$pass "
     fi
 
     # init connection and channels
     # we do it in XML cause otherwise we can't detect the end of data and so would need a read timeout O_o
     HANDLEID="MYSQL$RANDOM"
-    eval "coproc $HANDLEID { stdbuf -oL mysql -u $user $pass -h $host -D $db --force --unbuffered --xml -vvv 2>&1; }" # 2> /dev/null
+    eval "coproc $HANDLEID { stdbuf -oL mysql ${user:-}${pass:-}${host:-}${db:-} --force --unbuffered --xml -vvv 2>&1; }" # 2> /dev/null
     HANDLE=$(eval 'echo ${'${HANDLEID}'[0]}_${'${HANDLEID}'[1]}_${'${HANDLEID}'_PID}')
     mysql_capture_output 
     if mysql_check $HANDLE; then
       export HANDLE
+      out "successful connection established: $HANDLE"
       break
     else
-      err "ERROR: Connection failed to $user@$host->DB:$db!"
-      echo "$output"
+      err "Connection failed to $user@$host->DB:$db!"
+      echo "$mysql_connect_output"
       fail
     fi
   end_try
@@ -104,27 +121,27 @@ function mysql_connect {
 
 function mysql_capture_output {
 local handle=(${HANDLE//_/ }) line
-output=""
+mysql_connect_output=""
 while read -t 1 -ru ${handle[0]} line; do
-  output="$output$newline$line"
+  mysql_connect_output="$output$newline$line"
 done
 }
 
-# usage: HANDLE={handle} mysql_query {query}
+# usage: echo "{query}" | HANDLE={handle} mysql_query
 # return: $DATA[0] = affected rows/number of sets;
 #         $DATA[1] = key=>values pairs following
 #         $DATA[2] = key1; DATA[3] = val1
 #         $DATA[4] = key2; DATA[5] = val2 (depending on number of columns, rows)
 function mysql_query {
   local handle query affected line results_open row_open cols key val timed_out
-  query=$1
-  out "mysql_query ${query}"
+  query=$(</dev/stdin)
+  out "mysql_query\n${query}"
   try
-    if ! mysql_check $HANDLE; then
-      err "ERROR: Connection not open!"
+    handle=(${HANDLE//_/ })
+    if ! mysql_check; then
+      err "Connection not open!"
       return 1
     fi
-    handle=(${HANDLE//_/ })
 
     # use this to keep track of where you are when reading this data
     export current_row=0
@@ -220,10 +237,10 @@ function grab_row {
   current_row=$((current_row+1))
 }
 
-# usage: dbfetch_single_value {query}
+# usage: echo "{query}" | dbfetch_single_value
 #   sets r={value returned}
 function dbfetch_single_value {
-dbexecute "$1" || return 1
+mysql_query || return 1
 if more_rows_to_read; then 
   grab_row r || return 1
 fi
@@ -232,17 +249,17 @@ fi
 # usage: HANDLE={handle} mysql_close
 function mysql_close {
   local handle
-  if ! mysql_check $1; then
-    err "ERROR: Connection not open!"
+  if ! mysql_check; then
+    err "Connection not open!"
     return 1
   fi
   handle=(${1//_/ })
   echo "exit;" >&${handle[1]}
 
-  if ! mysql_check $1; then
+  if ! mysql_check; then
     return 0
   else
-    err "ERROR: Couldn't close connection!"
+    err "Couldn't close connection!"
     return 1
   fi
 }
