added more libs

diff --git a/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent b/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
--- a/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
+++ b/features/hosted_agents_connect_to_db_and_execute_tasks/bin/arms_agent
@@ -7,9 +7,11 @@ fi
 
 source lib/* || exit 1
 
+lock arms &>/dev/null || (echo "arms agent is already running"; exit 1)
+
 unset dbexecute
 dbexecute() {
-mysql -N -u$db_user -p$db_pass $db_host "${@:-}" || return 1
+mysql_query "$1" || return 1
 }
 
 if [ ! -f arms_agent.config ]; then
@@ -23,12 +25,36 @@ requireVar host_id db_host db_user db_pass || {
   exit 1
 }
 
-echo "
-  select tr.task_request_id, s.content, tr.parameters 
-  from task_request_not_done trnd 
-  inner join task_request tr using (task_request_id)
-  inner join script s using (script_id)
-  left join task_status_change tsc on trnd.task_request_id = tsc.task_request_id
-  where host_id = $host_id
-  and tsc.task_request_id is null
-  " | dbexecute
+unset establish_connection
+establish_connection() {
+  host=$db_host user=$db_user pass=$db_pass mysql_connect || return 1
+}
+
+establish_connection
+
+while true; do
+  # grab a task to do
+  dbexecute "
+    select tr.task_request_id, s.content, tr.parameters 
+    from task_request_not_done trnd 
+    inner join task_request tr using (task_request_id)
+    inner join script s using (script_id)
+    left join task_status_change tsc on trnd.task_request_id = tsc.task_request_id
+    where host_id = $host_id
+    and tsc.task_request_id is null
+    limit 1
+    " || (echo "failed to fetch new tasks."; fail)
+
+  if more_rows_to_read; then
+    grab_row task_request_id script_content script_parameters || (echo "failed to get row from array."; fail)
+    dbexecute "
+    " | (echo "failed to update task status."; fail)
+  else 
+    # there's nothing to do right now, let's rest a bit before trying again
+    random 10
+    sleep $((60+result))
+  fi
+done
+
+unlock arms &>/dev/null
+
