make test output debug mode

diff --git a/features/test/after b/features/test/after
--- a/features/test/after
+++ b/features/test/after
@@ -4,13 +4,25 @@ executeTests() {
 local path="$1" file dir
 try
   for file in $(find $path -mindepth 1 -maxdepth 1 -type f -printf "%f\n" | sort); do
-    out -n "$file: "
-    source $path/$file &>>$test_result_path || {
-      out_short "${RED}[Failed]${RESET}"
-      cat $test_result_path
-      fail
-    }
-    out_short "${GREEN}[Success]${RESET}"
+    if [ $debug -lt 10 ]; then
+      # normal mode: show test debug output only if it fails
+      out -n "$file: "
+      source $path/$file &>>$test_result_path || {
+        out_short "${RED}[Failed]${RESET}"
+        cat $test_result_path
+        fail
+      }
+      out_short "${GREEN}[Success]${RESET}"
+    else
+      # debugging mode, show test debug output as it happens
+      if source $path/$file; then
+        out "$file: ${GREEN}[Success]${RESET}"
+      else
+        out "$file: ${RED}[Failed]${RESET}"
+        cat $test_result_path
+        fail
+      fi
+    fi
   done; maybe_break
   
   for dir in $(find $path -mindepth 1 -maxdepth 1 -type d | sort); do
